[book]
title = "Notebook"
description = "Personal markdown notebook"
authors = ["Faione"]
language = "zh-CN"
src = "."

[build]
build-dir = "book"
create-missing = false

[output.html]
git-repository-url = "https://github.com/Faione/notebook"
edit-url-template = "https://github.com/Faione/notebook/edit/main/{path}"
site-url = "/notebook/"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
